constra/urls.py
from django.urls import path, include 
from .views import (
    home_view,
    about_view,
    comment_view,
    contact_view,
    faq_view,
    login_view,
    logout_view,
    news_detail,
    reg_view,
    typography_view,
    view_404,
    CustomDetail,
    CustomList,
)
from .models import (
    News,
    Pricing,
    Project,
    Service,
    Team,
    Testimonial,
)

app_name = 'constra'

urlpatterns = [
    path('', home_view, name='home'),
    path('404/', view_404, name='404'),
    path('about/', about_view, name='about'),
    path('comment/', comment_view, name='comment'),
    path('contact/', contact_view, name='contact'),
    path('faq/', faq_view, name='faq'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('news/<int:id>/', news_detail, name='news-detail'),
    path('reg/', reg_view, name='reg'),
    path('typography/', typography_view, name='typography'),

    # News urls
    path(
        'news-right/', 
        CustomList.as_view(
            model = News,
            template_name = 'constra/news/news-right.html'
        ), 
        name='news-right'
        ),
    path(
        'news-left/', 
        CustomList.as_view(
            model = News,
            template_name = 'constra/news/news-left.html'
        ), 
        name='news-left'
        ),
    # path(
    #     'news/<int:pk>/', 
    #     CustomDetail.as_view(
    #         model = News,
    #         template_name = 'constra/news/detail.html'
    #     ), 
    #     name='news-detail'
    #     ),

    # Pricing url
    path(
        'pricing/', 
        CustomList.as_view(
            model = Pricing,
            template_name = 'constra/other/pricing.html'
        ), 
        name='pricing'
        ),
    
    # Project urls
    path(
        'projects/', 
        CustomList.as_view(
            model = Project,
            template_name = 'constra/project/project.html'
        ), 
        name='project'
        ),
    path(
        'project/<int:pk>/', 
        CustomDetail.as_view(
            model = Project,
            template_name = 'constra/project/detail.html'
        ), 
        name='project-detail'
        ),

    # Service urls
    path(
        'service/', 
        CustomList.as_view(
            model = Service,
            template_name = 'constra/service/service.html'
        ), 
        name='service'
        ),
    path(
        'service/<int:pk>/', 
        CustomDetail.as_view(
            model = Service,
            template_name = 'constra/service/detail.html'
        ), 
        name='service-detail'
        ),

    # Team url
    path(
        'team/', 
        CustomList.as_view(
            model = Team,
            template_name = 'constra/team/team.html'
        ), 
        name='team'
        ),

    # testimonial url
    path(
        'testimonial/', 
        CustomList.as_view(
            model = Testimonial,
            template_name = 'constra/other/testimonial.html'
        ), 
        name='testimonial'
        ),
]

core/urls.py
from django.urls import path, include
from .views import (
    home,
    about,
    contact,
    portfolio,
    portfolio_detail,
)

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('portfolio/', portfolio, name='portfolio'),
    path('portfolio-detail/<int:id>/', portfolio_detail, name='portfolio-detail'),

    path('constra/', include('constra.urls')),
    path('educenter/', include('educenter.urls')),
    path('educenter/be/', include('eduback.urls')),
    path('educenter/account/', include('account.urls')),
    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('account/', include('account.urls', namespace='m-account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

constra/models.py
import email
from django.db import models
from django.contrib.auth.models import User

class CommonInfo(models.Model):
    name = models.CharField(max_length=100)
    about = models.TextField(default='Nats Stenman began his career in construction with boots on the ground')

    def __str__(self):
        return self.name
    
    class Meta:
        abstract = True
    
class Category(CommonInfo):
    about = None
    class Meta:
        verbose_name_plural = 'Categories'

class Comment(CommonInfo):
    post = models.ForeignKey('News', on_delete=models.CASCADE)
    n_name = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    website = models.URLField(null=True)


class Fact(CommonInfo):
    about = None
    number = models.IntegerField()
    image = models.ImageField(upload_to='images/icon-image/')

class News(CommonInfo):
    comments = models.IntegerField()
    comments_all = models.ManyToManyField(Comment)
    # author = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    image = models.ImageField(upload_to='images/news/')

    class Meta:
        verbose_name_plural = 'News'

class PricingFeatures(CommonInfo):
    pass

class Pricing(CommonInfo):
    about = None
    features = models.ManyToManyField(PricingFeatures)
    price = models.IntegerField()

class Project(CommonInfo):
    location = models.CharField(max_length=100, default='McLean, VA')
    client = models.CharField(max_length=100, default='Pransbay Powers Authority')
    architect = models.CharField(max_length=100, default='Dlarke Pelli Incorp')
    size = models.IntegerField()
    image = models.ImageField(upload_to='images/projects/')
    categories = models.ManyToManyField(Category)

class Service(CommonInfo):
    solutions = models.ManyToManyField('Solution')
    image1 = models.ImageField(upload_to='images/services/')
    image2 = models.ImageField(upload_to='images/services/')
    icon = models.ImageField(upload_to='images/services/')

class Solution(CommonInfo):
    about = None

class Team(CommonInfo):
    position = models.CharField(max_length=100, default='Innovation Officer')
    image = models.ImageField(upload_to='images/team/')

class Testimonial(CommonInfo):
    position = models.CharField(max_length=100, default='CEO, First Choice Group')
    image = models.ImageField(upload_to='images/clients/')

constra/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import (
    Comment,
    Fact,
    News, 
    Project,
)
from django.views.generic import ListView, DetailView

def home_view(request):
    context = {
        'facts': Fact.objects.all(),
        'object_list': Project.objects.all(),
    }
    return render(request, 'constra/home/home.html', context)

def view_404(request):
    return render(request, 'constra/other/404.html',{'msg':'Oops... Page Not Found!'})

def about_view(request):
    context = {
        'facts': Fact.objects.all(),
    }
    return render(request, 'constra/about/about.html', context)

def comment_view(request):
    usn = request.POST['cName']
    nc = User.username
    email = request.POST['cEmail']
    website = request.POST['Website']
    content = request.POST['Content']
    post = news_detail(request)[1]
    cm = Comment.objects.create(name=usn,email=email,about=content,website=website,n_name=nc,post=post)
    cm.save()
    return redirect('./')

def contact_view(request):
    return render(request, 'constra/other/contact.html')

def faq_view(request):
    return render(request, 'constra/other/faq.html')

def login_view(request):
    usn = request.POST['Name']
    passw = request.POST['Passw']
    user = authenticate(username=usn,password=passw)
    if user is not None:
        login(request, user)
        return redirect('home:home')
    else:
        return render(request, 'constra/other/404.html' ,{'msg':'Invalid login. Check credentials!'})

def logout_view(request):
    logout(request)
    return redirect('../')

def reg_view(request):
    usn = request.POST['sName']
    passw = request.POST['sPassw']
    email = request.POST['Email']
    user = User.objects.create_user(username=usn,password=passw,email=email)
    user.save()
    if user is not None:
        login(request, user)
        return redirect('home:home')


def typography_view(request):
    return render(request, 'constra/other/typography.html')

def news_detail(request, id=1):
    try:
        object = News.objects.get(id=id)
        if request.POST:
            usn = request.POST['cName']
            email = request.POST['cEmail']
            website = request.POST['Website']
            content = request.POST['Content']
            post = object
            cm = Comment.objects.create(name=usn,email=email,about=content,n_name=request.user,website=website,post=post)
            cm.save()
            return redirect('./')
        comments = Comment.objects.filter(post=object)
        object.comments_all.set(comments)
        context = {
            'object': object,
            'comments': comments,
            'news_list': News.objects.all()
        }
        return render(request, 'constra/news/detail.html', context)
    except:
        return render(request, 'constra/other/404.html' ,{'msg':'That page cannot be accessed!'})

# Custom Views
class CustomList(ListView):
    pass

class CustomDetail(DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['news_list'] = News.objects.all()
        except:
            pass
        return context

templates/constra/news/detail.html
{% extends 'constra/base/base.html' %}
{% load static %}
{% block content %}

<div id="banner-area" class="banner-area" style="background-image:url({% static 'images/banner/banner1.jpg'%})">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">News</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">Home</a></li>
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">News</a></li>
                      <li class="breadcrumb-item active" aria-current="page">News Right sidebar</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 


<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">

      <div class="col-lg-8 mb-5 mb-lg-0">

        <div class="post-content post-single">
          <div class="post-media post-image">
            <img loading="lazy" src="{{object.image.url}}" class="img-fluid" alt="post-image">
          </div>

          <div class="post-body">
            <div class="entry-header">
              <div class="post-meta">
                <span class="post-author">
                  <i class="far fa-user"></i><a href="#"> {{object.author}}</a>
                </span>
                <span class="post-cat">
                  <i class="far fa-folder-open"></i><a href="#"> News</a>
                </span>
                <span class="post-meta-date"><i class="far fa-calendar"></i>{{object.date}}</span>
                <span class="post-comment"><i class="far fa-comment"></i> {{object.comments}}<a href="#"
                    class="comments-link">Comments</a></span>
              </div>
              <h2 class="entry-title">
                {{object.name}}
              </h2>
            </div><!-- header end -->

            <div class="entry-content">

              <p>{{object.about}}</p>
              <p>{{object.about}}</p>

              <blockquote>
                <p>Eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.<cite>-
                    Anger Mathe</cite></p>
                    
                  </blockquote>
                  
                <p>{{object.about}}</p>
            </div>

            <div class="tags-area d-flex align-items-center justify-content-between">
              <div class="post-tags">
                <a href="#">Construction</a>
                <a href="#">Safety</a>
                <a href="#">Planning</a>
              </div>
              <div class="share-items">
                <ul class="post-social-icons list-unstyled">
                  <li class="social-icons-head">Share:</li>
                  <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fab fa-google-plus"></i></a></li>
                  <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>

          </div><!-- post-body end -->
        </div><!-- post content end -->

        <div class="author-box d-nlock d-sm-flex">
          <div class="author-img mb-4 mb-md-0">
            <img loading="lazy" src="{% static 'images/news/avator1.png'%}" alt="author">
          </div>
          <div class="author-info">
            <h3>Elton Themen<span>Site Engineer</span></h3>
            <p class="mb-2">Lisicing elit, sed do eiusmod tempor ut labore et dolore magna aliqua. Ut enim ad vene minim
              veniam, quis nostrud exercitation nisi ex ea commodo.</p>
            <p class="author-url mb-0">Website: <span><a href="#">http://www.example.com</a></span></p>

          </div>
        </div> <!-- Author box end -->

        <!-- Post comment start -->
        <div id="comments" class="comments-area">
          <h3 class="comments-heading">07 Comments</h3>

          <ul class="comments-list">
            {% for c in object.comments_all.all %}
            <li>
              <div class="comment d-flex">
                <img loading="lazy" class="comment-avatar" alt="author" src="{% static 'images/news/avator1.png'%}">
                <div class="comment-body">
                  <div class="meta-data">
                    <span class="comment-author mr-3">{{c.name}} {{c.n_name}}</span>
                    <span class="comment-date float-right">January 17, 2016 at 1:38 pm</span>
                  </div>
                  <div class="comment-content">
                    <p>{{c.about}}</p>
                  </div>
                  <div class="text-left">
                    <a class="comment-reply font-weight-bold" href="#">Reply</a>
                  </div>
                </div>
              </div><!-- Comments end -->

              {% comment %} <ul class="comments-reply">
                <li>
                  <div class="comment d-flex">
                    <img loading="lazy" class="comment-avatar" alt="author" src="images/news/avator2.png">
                    <div class="comment-body">
                      <div class="meta-data">
                        <span class="comment-author mr-3">Tom Harnandez</span>
                        <span class="comment-date float-right">January 17, 2016 at 1:38 pm</span>
                      </div>
                      <div class="comment-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                          laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehen.</p>
                      </div>
                      <div class="text-left">
                        <a class="comment-reply font-weight-bold" href="#">Reply</a>
                      </div>
                    </div>
                  </div><!-- Comments end -->
                </li>
              </ul><!-- comments-reply end -->
               {% endcomment %}
            </li><!-- Comments-list li end -->
            {% endfor %}
          </ul><!-- Comments-list ul end -->
        </div><!-- Post comment end -->

        <div class="comments-form border-box">
          <h3 class="title-normal">Add a comment</h3>

          <form role="form" action="./" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="message" class="w-100"><textarea class="form-control required-field" id="message" name="Content" placeholder="Your Comment" rows="10" required></textarea></label>
                </div>
              </div><!-- Col 12 end -->

              <div class="col-md-4">
                <div class="form-group">
                  <label for="name" class="w-100"><input class="form-control" name="cName" id="Name" placeholder="Your Name" type="text" required></label>
                </div>
              </div><!-- Col 4 end -->

              <div class="col-md-4">
                <div class="form-group">
                  <label for="email" class="w-100"><input class="form-control" name="cEmail" id="email" placeholder="Your Email" type="email" required></label>
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="website" class="w-100"><input class="form-control" id="website" name="Website" placeholder="Your Website" type="text"></label>
                </div>
              </div>

            </div><!-- Form row end -->
            <div class="clearfix">
              <button class="btn btn-primary" type="submit" aria-label="post-comment">Post Comment</button>
            </div>
          </form><!-- Form end -->
        </div><!-- Comments form end -->
      </div><!-- Content Col end -->

      <div class="col-lg-4">

        <div class="sidebar sidebar-right">
          {% include 'news/recent.html' %}

        </div><!-- Sidebar end -->
      </div><!-- Sidebar Col end -->

    </div><!-- Main row end -->

  </div><!-- Conatiner end -->
</section><!-- Main container end -->

{% endblock content %}

templates/constra/news/list.html
{% for o in object_list %}
<div class="post">
    <div class="post-media post-image">
    <img loading="lazy" src="{{o.image.url}}" class="img-fluid" alt="post-image">
    </div>

    <div class="post-body">
    <div class="entry-header">
        <div class="post-meta">
        <span class="post-author">
            <i class="far fa-user"></i><a href="#"> {{o.author}}</a>
        </span>
        <span class="post-cat">
            <i class="far fa-folder-open"></i><a href="#"> News</a>
        </span>
        <span class="post-meta-date"><i class="far fa-calendar"></i> {{o.date}}</span>
        <span class="post-comment"><i class="far fa-comment"></i> {{o.comments}}<a href="#"
            class="comments-link">Comments</a></span>
        </div>
        <h2 class="entry-title">
        <a href="{% url 'constra:news-detail' o.id %}">{{o.name}}</a>
        </h2>
    </div><!-- header end -->

    <div class="entry-content">
        <p>{{o.about | truncatewords:"65"}}.</p>
    </div>

    <div class="post-footer">
        <a href="{% url 'constra:news-detail' o.id %}" class="btn btn-primary">Continue Reading</a>
    </div>

    </div><!-- post-body end -->
</div><!-- 1st post end -->
{% endfor %}
<nav class="paging" aria-label="Page navigation example">
    <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#"><i class="fas fa-angle-double-left"></i></a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#"><i class="fas fa-angle-double-right"></i></a></li>
    </ul>
</nav>

templates/constra/news/news-left.html
{% extends 'constra/base/base.html' %}
{% load static %}
{% block content %}

<div id="banner-area" class="banner-area" style="background-image:url({% static 'images/banner/banner1.jpg'%})">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">News</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">Home</a></li>
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">News</a></li>
                      <li class="breadcrumb-item active" aria-current="page">News left sidebar</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 

<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">

      <div class="col-lg-4 order-1 order-lg-0">

        <div class="sidebar sidebar-left">
            {% include 'constra/news/recent.html' %}
        </div><!-- Sidebar end -->
      </div><!-- Sidebar Col end -->

      <div class="col-lg-8 mb-5 mb-lg-0 order-0 order-lg-1">
        {% include "constra/news/list.html" %}

      </div><!-- Content Col end -->

    </div><!-- Main row end -->

  </div><!-- Container end -->
</section><!-- Main container end -->


{% endblock content %}

templates/constra/news/news-right.html
{% extends 'constra/base/base.html' %}
{% load static %}
{% block content %}

<div id="banner-area" class="banner-area" style="background-image:url({% static 'images/banner/banner1.jpg'%})">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">News</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">Home</a></li>
                      <li class="breadcrumb-item"><a href="{% url 'constra:home' %}">News</a></li>
                      <li class="breadcrumb-item active" aria-current="page">News Right sidebar</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 

<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">

      <div class="col-lg-8 mb-5 mb-lg-0">
        {% include "constra/news/list.html" %}
      </div><!-- Content Col end -->

      <div class="col-lg-4">

        <div class="sidebar sidebar-right">
          {% include 'constra/news/recent.html' %}
        </div><!-- Sidebar end -->
      </div><!-- Sidebar Col end -->

    </div><!-- Main row end -->

  </div><!-- Container end -->
</section><!-- Main container end -->


{% endblock content %}

templates/constra/news/recent.html
<div class="widget recent-posts">
    <h3 class="widget-title">Recent Posts</h3>
    <ul class="list-unstyled">
        {% for o in news_list %}
        {% if forloop.revcounter < 4 %}
        <li class="d-flex align-items-center">
        <div class="posts-thumb">
            <a href="#"><img loading="lazy" alt="img" src="{{o.image.url}}"></a>
        </div>
        <div class="post-info">
            <h4 class="entry-title">
            <a href="#">{{o.name}}</a>
            </h4>
        </div>
        </li><!-- 1st post end-->
        {% endif %}
        {% endfor %}

    </ul>
</div><!-- Recent post end -->
{% include 'constra/news/widgets.html' %}

templates/constra/news/widgets.html
<div class="widget">
    <h3 class="widget-title">Categories</h3>
    <ul class="arrow nav nav-tabs">
        <li><a href="#">Construction</a></li>
        <li><a href="#">Commercial</a></li>
        <li><a href="#">Building</a></li>
        <li><a href="#">Safety</a></li>
        <li><a href="#">Structure</a></li>
    </ul>
    </div><!-- Categories end -->

    <div class="widget">
    <h3 class="widget-title">Archives </h3>
    <ul class="arrow nav nav-tabs">
        <li><a href="#">Feburay 2016</a></li>
        <li><a href="#">January 2016</a></li>
        <li><a href="#">December 2015</a></li>
        <li><a href="#">November 2015</a></li>
        <li><a href="#">October 2015</a></li>
    </ul>
    </div><!-- Archives end -->

    <div class="widget widget-tags">
    <h3 class="widget-title">Tags </h3>

    <ul class="list-unstyled">
        <li><a href="#">Construction</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Project</a></li>
        <li><a href="#">Building</a></li>
        <li><a href="#">Finance</a></li>
        <li><a href="#">Safety</a></li>
        <li><a href="#">Contracting</a></li>
        <li><a href="#">Planning</a></li>
    </ul>
</div><!-- Tags end -->