account/urls.py
from django.urls import path
from .views import login_view, create_view, logout_view, profile_view, profile_edit, EditUser

app_name = 'account'
urlpatterns = [    
    path('login/', login_view, name='login'),
    path('create-user/', create_view, name='create-user'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('edit/<int:pk>/', EditUser.as_view(), name='edit')
]

core/urls.py
from django.urls import path, include
from .views import (
    home,
    about,
    contact,
    portfolio,
    portfolio_detail,
)

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('portfolio/', portfolio, name='portfolio'),
    path('portfolio-detail/<int:id>/', portfolio_detail, name='portfolio-detail'),

    path('constra/', include('constra.urls')),
    path('educenter/', include('educenter.urls')),
    path('educenter/be/', include('eduback.urls')),
    path('educenter/account/', include('account.urls')),
    
]

eduback/urls.py
from django.urls import path, include
from .forms import (
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
)

from educenter.models import (
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
)

from .views import (
    home,
    CustomCreate,
    CustomDetail,
    CustomEdit,
    # about, 
    # blog, 
    # course, 
    # event,
    # notice, 
    # research, 
    # scholarship, 
    # teacher,
)

li0 = [
    'about',
    'blog',
    'course',
    'event',
    'funfact',
    'interest',
    'notice',
    'requirement',
    'research',
    'scholarship',
    'school',
    'teacher'
]


li1 = [
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
]

li2 = [
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
]

length1 = [0, 1, 2, 3, 6, 8, 9, 11]
length2 = [4, 5, 7, 8, 9, 10]

app_name = 'backend'


urlpatterns = [
    path('', home, name='home'),
    path('account/', include('account.urls', namespace='b-account')),
]

for l in length1:
    urlpatterns.append(
        path(
                f"{li0[l]}/",
                CustomCreate.as_view(
                    model = li1[l],
                    form_class = li2[l],
                    template_name = f"educenter/core/{li0[l]}.html", 
                    success_url = f"#",
                ),
                name = f"{li0[l]}"
            )
    ),
    if l not in length2:
        urlpatterns.append(
            path(
                    f"{li0[l]}/<int:pk>/",
                    CustomDetail.as_view(
                        model = li1[l],
                        template_name = f"educenter/core/{li0[l]}-single.html", 
                    ),
                    name = f"{li0[l]}-single"
                )
        )

for l in length2:
    if l not in length1:
        urlpatterns.append(
            path(
                    f"{li0[l]}/",
                    CustomCreate.as_view(
                        model = li1[l],
                        form_class = li2[l],
                        template_name = "educenter/be/list.html", 
                        success_url = f"#",
                    ),
                    name = f"{li0[l]}"
                )
        ),
    urlpatterns.append(
        path(
                f"{li0[l]}/<int:pk>/",
                CustomDetail.as_view(
                    model = li1[l],
                    template_name = f"educenter/be/detail.html", 
                ),
                name = f"{li0[l]}-single"
            )
    ),

for l in range(12):
    urlpatterns.append(
        path(
                f"{li0[l]}/<int:pk>/edit",
                CustomEdit.as_view(
                    model = li1[l],
                    success_url = f"../",
                ),
                name = f"{li0[l]}-edit"
            )
    ),

educenter/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .models import (
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher
)
from .views import (
    about_view, 
    # blog_view, 
    # teacher_view, 
    contact_view,
    # course_view, 
    home_view, 
    # notice_view, 
    # event_view, 
    # research_view, 
    # scholarship_view,
    CustomList,
    CustomDetail
)

app_name = "educenter"
# from .views import home_view

li1 = [
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher,
]

li2 = [
    'blog',
    'course',
    'event',
    'notice',
    'research',
    'scholarship',
    'teacher',
]

length = [0, 1, 2, 3, 4, 5, 6]
length1 = [0, 1, 2, 3, 6]

urlpatterns = [
        path('', home_view, name='home'),
        path('about/', about_view, name='about'),
        path('contact/', contact_view, {'li':'contact.html'}, name='contact' ),

        # path('blog-single/<int:pk>', blog_view, {'li':'blog-single.html'}, name='blog-single' ),
        # path('blog/', blog_view, {'li':'blog.html'}, name='blog' ),
        
        # path('teacher-single/<int:pk>', teacher_view, {'li':'teacher-single.html'}, name='teacher-single' ),
        # path('teacher/', teacher_view, {'li':'teacher.html'}, name='teacher' ),
        
        # path('notice-single/', notice_view, {'li':'notice-single.html'}, name='notice-single' ),
        # path('notice/', notice_view, {'li':'notice.html'}, name='notice' ),
        
        # path('course-single/<int:pk>', course_view, {'li':'course-single.html'}, name='course-single' ),
        # path('courses/', course_view, {'li':'courses.html'}, name='courses' ),
        
        # path('event-single/<int:pk>', event_view, {'li':'event-single.html'}, name='event-single' ),
        # path('events/', event_view, {'li':'events.html'}, name='events' ),

        # path('research/', research_view, {'li':'research.html'}, name='research' ),
        # path('scholarship/', scholarship_view, {'li':'scholarship.html'}, name='scholarship' ),

        # path(
        #     'teacher/', 
        #     CustomList.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher.html'
        #     ), 
        #     name = 'teacher'
        # ),
        # path(
        #     'teacher-single/<int:pk>',
        #     CustomDetail.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher-single.html'
        #     ),
        #     name = 'teacher-single'
        # ),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for i in length :
    urlpatterns.append(
        path(
            li2[i]+'/', 
            CustomList.as_view(
                model = li1[i],
                template_name = 'educenter/core/'+li2[i]+'.html'
            ), 
            name = li2[i]
        )      
    )

for n in length1:
    urlpatterns.append(
        path(
            li2[n]+'-single/<int:pk>',
            CustomDetail.as_view(
                model = li1[n],
                template_name = 'educenter/core/'+li2[n]+'-single.html'
            ),
            name = li2[n]+'-single'
        )
    )

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('account/', include('account.urls', namespace='m-account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models


class ProjectType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=100)
    project_type  = models.ForeignKey(ProjectType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/portfolio')
    year = models.DateField()
    client = models.CharField(max_length=100)
    about = models.TextField(
        default="""
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi eligendi fugiat ad cupiditate hic, eum debitis ipsum, quos non mollitia. Commodi suscipit obcaecati et, aperiam quas vero quo, labore tempore.

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam debitis beatae doloremque cupiditate vel repellat nam est voluptates, magnam quod explicabo fugit, quidem.
        """)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    context = {
        'projects': Project.objects.all()
    }
    return render(request, 'home.html', context)

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def portfolio(request):
    context = {
        'projects': Project.objects.all()
    }
    return render(request, 'portfolio/portfolio.html', context)


def portfolio_detail(request, id=1):
    context = {
        'project': Project.objects.get(id=id)
    }
    return render(request, 'portfolio/portfolio-detail.html', context)

templates/educenter/core/base/footer.html
{% load static %}

<!-- footer -->
<footer>
  <!-- newsletter -->
  <div class="newsletter">
    <div class="container">
      <div class="row">
        <div class="col-md-9 ml-auto bg-primary py-5 newsletter-block">
          <h3 class="text-white">Subscribe Now</h3>
          <form action="#">
            <div class="input-wrapper">
              <input type="email" class="form-control border-0" id="newsletter" name="newsletter" placeholder="Enter Your Email...">
              <button type="submit" value="send" class="btn btn-primary">Join</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- footer content -->
  <div class="footer bg-footer section border-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-sm-8 mb-5 mb-lg-0">
          <!-- logo -->
          <a class="logo-footer" href="{% url 'educenter:home' %}"><img class="img-fluid mb-4" src="{% static 'images/logo-edu.png'%}" alt="logo"></a>
          <ul class="list-unstyled">
            <li class="mb-2">23621 15 Mile Rd #C104, Clinton MI, 48035, New York, USA</li>
            <li class="mb-2">+1 (2) 345 6789</li>
            <li class="mb-2">+1 (2) 345 6789</li>
            <li class="mb-2">contact@yourdomain.com</li>
          </ul>
        </div>
        <!-- company -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">COMPANY</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:about' %}">About Us</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:teacher' %}">Our Teacher</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:contact' %}">Contact</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:blog' %}">Blog</a></li>
          </ul>
        </div>
        <!-- links -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">LINKS</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:course' %}">Courses</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:event' %}">Events</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:notice' %}">Notice</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'educenter:research' %}">Research</a></li>
          </ul>
        </div>
        <!-- support -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">SUPPORT</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="#">Forums</a></li>
            <li class="mb-3"><a class="text-color" href="#">Documentation</a></li>
            <li class="mb-3"><a class="text-color" href="#">Language</a></li>
            <li class="mb-3"><a class="text-color" href="#">Release Status</a></li>
          </ul>
        </div>
        <!-- support -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">RECOMMEND</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="#">WordPress</a></li>
            <li class="mb-3"><a class="text-color" href="#">LearnPress</a></li>
            <li class="mb-3"><a class="text-color" href="#">WooCommerce</a></li>
            <li class="mb-3"><a class="text-color" href="#">bbPress</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- copyright -->
  <div class="copyright py-4 bg-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 text-sm-left text-center">
          <p class="mb-0">Copyright
            <script>
              var CurrentYear = new Date().getFullYear()
              document.write(CurrentYear)
            </script> 
            © themefisher</p>
        </div>
        <div class="col-sm-5 text-sm-right text-center">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-facebook text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-twitter-alt text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-linkedin text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-instagram text-primary"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- /footer -->

templates/educenter/core/base/header.html
{% load static %}
{% block header %}
<header class="fixed-top header">
  {% include 'educenter/core/base/topheader.html' %}
  <!-- navbar -->
  <div class="navigation w-100">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark p-0">
        <a class="navbar-brand" href="{% url 'educenter:home' %}"><img src="{% static 'images/logo-edu.png' %}" alt="logo"></a>
        <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
          aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navigation">
        {% if plat == 'educenter' %}
        {% include 'educenter/core/base/nav.html' %}
        {% else %}
        {% include 'educenter/be/nav.html' %}
        {% endif %}
        </div>
      </nav>
    </div>
  </div>
</header>
{% endblock header %}

templates/educenter/core/base/nav.html
<ul class="navbar-nav ml-auto text-center">
    <li class="nav-item active">
        <a class="nav-link" href="{% url plat|add:':home' %}">Home</a>
    </li>
    <li class="nav-item @@about">
        <a class="nav-link" href="{% url plat|add:':about' %}">About</a>
    </li>
    <li class="nav-item @@courses">
        <a class="nav-link" href="{% url plat|add:':course' %}">COURSES</a>
    </li>
    <li class="nav-item @@events">
        <a class="nav-link" href="{% url plat|add:':event' %}">EVENTS</a>
    </li>
    <li class="nav-item @@blog">
        <a class="nav-link" href="{% url plat|add:':blog' %}">BLOG</a>
    </li>
    <li class="nav-item dropdown view">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        Pages
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url plat|add:':teacher' %}">Teacher</a>
        <a class="dropdown-item" href="{% url plat|add:':teacher-single' 1 %}">Teacher Single</a>
        <a class="dropdown-item" href="{% url plat|add:':notice' %} ">Notice</a>
        <a class="dropdown-item" href="{% url plat|add:':notice-single' 1 %}">Notice Details</a>
        <a class="dropdown-item" href="{% url plat|add:':research' %}">Research</a>
        <a class="dropdown-item" href="{% url plat|add:':scholarship' %}">Scholarship</a>
        <a class="dropdown-item" href="{% url plat|add:':course-single' 1 %}">Course Details</a>
        <a class="dropdown-item" href="{% url plat|add:':event-single' 1 %}">Event Details</a>
        <a class="dropdown-item" href="{% url plat|add:':blog-single' 1 %}">Blog Details</a>
        </div>
    </li>
    <li class="nav-item @@contact">
        <a class="nav-link" href="{% url plat|add:':contact' %}">CONTACT</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item @@contact">
        <a class="nav-link" href="{% url 'backend:home' %}">BACKEND</a>
    {% endif %}
    </li>
    </ul>

templates/educenter/core/base/topheader.html
  <!-- top header -->
  <div class="top-header py-2 bg-white">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-lg-4 text-center text-lg-left">
          <a class="text-color mr-3" href="callto:+254747410095"><strong>CALL</strong> +254 747 410095</a>
          <ul class="list-inline d-inline">
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-facebook"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-twitter-alt"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-linkedin"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-instagram"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-8 text-center text-lg-right">
          <ul class="list-inline">          
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url plat|add:':notice' %}">notice</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url plat|add:':research' %}">research</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url plat|add:':scholarship' %}">SCHOLARSHIP</a></li>
            {% if user.is_authenticated %}
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#logoutModal">logout</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'account:profile' %}">{{user}}</a></li>
            {% else %}
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#loginModal">log</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#signupModal">register</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>