constra/urls.py
from django.urls import path, include 
from .views import (
    home_view,
    about_view,
    comment_view,
    contact_view,
    faq_view,
    login_view,
    logout_view,
    news_detail,
    reg_view,
    typography_view,
    view_404,
    CustomDetail,
    CustomList,
)
from .models import (
    News,
    Pricing,
    Project,
    Service,
    Team,
    Testimonial,
)

app_name = 'constra'

urlpatterns = [
    path('', home_view, name='home'),
    path('404/', view_404, name='404'),
    path('about/', about_view, name='about'),
    path('comment/', comment_view, name='comment'),
    path('contact/', contact_view, name='contact'),
    path('faq/', faq_view, name='faq'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('news/<int:id>/', news_detail, name='news-detail'),
    path('reg/', reg_view, name='reg'),
    path('typography/', typography_view, name='typography'),

    # News urls
    path(
        'news-right/', 
        CustomList.as_view(
            model = News,
            template_name = 'constra/news/news-right.html'
        ), 
        name='news-right'
        ),
    path(
        'news-left/', 
        CustomList.as_view(
            model = News,
            template_name = 'constra/news/news-left.html'
        ), 
        name='news-left'
        ),
    # path(
    #     'news/<int:pk>/', 
    #     CustomDetail.as_view(
    #         model = News,
    #         template_name = 'constra/news/detail.html'
    #     ), 
    #     name='news-detail'
    #     ),

    # Pricing url
    path(
        'pricing/', 
        CustomList.as_view(
            model = Pricing,
            template_name = 'constra/other/pricing.html'
        ), 
        name='pricing'
        ),
    
    # Project urls
    path(
        'projects/', 
        CustomList.as_view(
            model = Project,
            template_name = 'constra/project/project.html'
        ), 
        name='project'
        ),
    path(
        'project/<int:pk>/', 
        CustomDetail.as_view(
            model = Project,
            template_name = 'constra/project/detail.html'
        ), 
        name='project-detail'
        ),

    # Service urls
    path(
        'service/', 
        CustomList.as_view(
            model = Service,
            template_name = 'constra/service/service.html'
        ), 
        name='service'
        ),
    path(
        'service/<int:pk>/', 
        CustomDetail.as_view(
            model = Service,
            template_name = 'constra/service/detail.html'
        ), 
        name='service-detail'
        ),

    # Team url
    path(
        'team/', 
        CustomList.as_view(
            model = Team,
            template_name = 'constra/team/team.html'
        ), 
        name='team'
        ),

    # testimonial url
    path(
        'testimonial/', 
        CustomList.as_view(
            model = Testimonial,
            template_name = 'constra/other/testimonial.html'
        ), 
        name='testimonial'
        ),
]

core/urls.py
from django.urls import path, include
from .views import (
    home,
    about,
    contact,
    portfolio,
    portfolio_detail,
)

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('portfolio/', portfolio, name='portfolio'),
    path('portfolio-detail/<int:id>/', portfolio_detail, name='portfolio-detail'),

    path('constra/', include('constra.urls')),
    path('educenter/', include('educenter.urls')),
    path('educenter/be/', include('eduback.urls')),
    path('educenter/account/', include('account.urls')),
    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('account/', include('account.urls', namespace='m-account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

constra/models.py
import email
from django.db import models
from django.contrib.auth.models import User

class CommonInfo(models.Model):
    name = models.CharField(max_length=100)
    about = models.TextField(default='Nats Stenman began his career in construction with boots on the ground')

    def __str__(self):
        return self.name
    
    class Meta:
        abstract = True
    
class Category(CommonInfo):
    about = None
    class Meta:
        verbose_name_plural = 'Categories'

class Comment(CommonInfo):
    post = models.ForeignKey('News', on_delete=models.CASCADE)
    n_name = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    website = models.URLField(null=True)


class Fact(CommonInfo):
    about = None
    number = models.IntegerField()
    image = models.ImageField(upload_to='images/icon-image/')

class News(CommonInfo):
    comments = models.IntegerField()
    comments_all = models.ManyToManyField(Comment)
    # author = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    image = models.ImageField(upload_to='images/news/')

    class Meta:
        verbose_name_plural = 'News'

class PricingFeatures(CommonInfo):
    pass

class Pricing(CommonInfo):
    about = None
    features = models.ManyToManyField(PricingFeatures)
    price = models.IntegerField()

class Project(CommonInfo):
    location = models.CharField(max_length=100, default='McLean, VA')
    client = models.CharField(max_length=100, default='Pransbay Powers Authority')
    architect = models.CharField(max_length=100, default='Dlarke Pelli Incorp')
    size = models.IntegerField()
    image = models.ImageField(upload_to='images/projects/')
    categories = models.ManyToManyField(Category)

class Service(CommonInfo):
    solutions = models.ManyToManyField('Solution')
    image1 = models.ImageField(upload_to='images/services/')
    image2 = models.ImageField(upload_to='images/services/')
    icon = models.ImageField(upload_to='images/services/')

class Solution(CommonInfo):
    about = None

class Team(CommonInfo):
    position = models.CharField(max_length=100, default='Innovation Officer')
    image = models.ImageField(upload_to='images/team/')

class Testimonial(CommonInfo):
    position = models.CharField(max_length=100, default='CEO, First Choice Group')
    image = models.ImageField(upload_to='images/clients/')

constra/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import (
    Comment,
    Fact,
    News, 
    Project,
)
from django.views.generic import ListView, DetailView

def home_view(request):
    context = {
        'facts': Fact.objects.all(),
        'object_list': Project.objects.all(),
    }
    return render(request, 'constra/home/home.html', context)

def view_404(request):
    return render(request, 'constra/other/404.html',{'msg':'Oops... Page Not Found!'})

def about_view(request):
    context = {
        'facts': Fact.objects.all(),
    }
    return render(request, 'constra/about/about.html', context)

def comment_view(request):
    usn = request.POST['cName']
    nc = User.username
    email = request.POST['cEmail']
    website = request.POST['Website']
    content = request.POST['Content']
    post = news_detail(request)[1]
    cm = Comment.objects.create(name=usn,email=email,about=content,website=website,n_name=nc,post=post)
    cm.save()
    return redirect('./')

def contact_view(request):
    return render(request, 'constra/other/contact.html')

def faq_view(request):
    return render(request, 'constra/other/faq.html')

def login_view(request):
    usn = request.POST['Name']
    passw = request.POST['Passw']
    user = authenticate(username=usn,password=passw)
    if user is not None:
        login(request, user)
        return redirect('home:home')
    else:
        return render(request, 'constra/other/404.html' ,{'msg':'Invalid login. Check credentials!'})

def logout_view(request):
    logout(request)
    return redirect('../')

def reg_view(request):
    usn = request.POST['sName']
    passw = request.POST['sPassw']
    email = request.POST['Email']
    user = User.objects.create_user(username=usn,password=passw,email=email)
    user.save()
    if user is not None:
        login(request, user)
        return redirect('home:home')


def typography_view(request):
    return render(request, 'constra/other/typography.html')

def news_detail(request, id=1):
    try:
        object = News.objects.get(id=id)
        if request.POST:
            usn = request.POST['cName']
            email = request.POST['cEmail']
            website = request.POST['Website']
            content = request.POST['Content']
            post = object
            cm = Comment.objects.create(name=usn,email=email,about=content,n_name=request.user,website=website,post=post)
            cm.save()
            return redirect('./')
        comments = Comment.objects.filter(post=object)
        object.comments_all.set(comments)
        context = {
            'object': object,
            'comments': comments,
            'news_list': News.objects.all()
        }
        return render(request, 'constra/news/detail.html', context)
    except:
        return render(request, 'constra/other/404.html' ,{'msg':'That page cannot be accessed!'})

# Custom Views
class CustomList(ListView):
    pass

class CustomDetail(DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['news_list'] = News.objects.all()
        except:
            pass
        return context

templates/constra/project/detail.html
{% extends 'constra/base/base.html' %}
{% load static %}
{% block content %}

<section id="main-container" class="main-container">
  <div class="container">

    <div class="row">
      <div class="col-lg-8">
        <div id="page-slider" class="page-slider small-bg">
          <div class="item">
            <img loading="lazy" class="img-fluid" src="{{object.image.url}}" alt="project-image" />
          </div>

          <div class="item">
            <img loading="lazy" class="img-fluid" src="{{object.image.url}}" alt="project-image" />
          </div>
        </div><!-- Page slider end -->
      </div><!-- Slider col end -->

      <div class="col-lg-4 mt-5 mt-lg-0">

        <h3 class="column-title mrt-0">{{object.name}}</h3>
        <p>{{object.about}}</p>

        <ul class="project-info list-unstyled">
          <li>
            <p class="project-info-label">Client</p>
            <p class="project-info-content">{{object.client}}</p>
          </li>
          <li>
            <p class="project-info-label">Architect</p>
            <p class="project-info-content">{{object.architect}}</p>
          </li>
          <li>
            <p class="project-info-label">Location</p>
            <p class="project-info-content">{{object.location}}</p>
          </li>
          <li>
            <p class="project-info-label">Size</p>
            <p class="project-info-content">{{object.size}} SF</p>
          </li>
          <li>
            <p class="project-info-label">Year Completed</p>
            <p class="project-info-content">{{object.year}}</p>
          </li>
          <li>
            <p class="project-info-label">Categories</p>
            <p class="project-info-content">{% for c in object.category.all %}{{c.name}}{% if forloop.counter == 1 %}, {% endif %}{% endfor %}</p>
          </li>
          <li>
            <p class="project-link">
              <a class="btn btn-primary" target="_blank" href="#">View Project</a>
            </p>
          </li>
        </ul>

      </div><!-- Content col end -->

    </div><!-- Row end -->

  </div><!-- Conatiner end -->
</section><!-- Main container end -->


{% endblock %}

templates/constra/project/list.html
{% load static %}
<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="shuffle-btn-group">
          <label class="active" for="all">
            <input type="radio" name="shuffle-filter" id="all" value="all" checked="checked">Show All
          </label>
          <label for="commercial">
            <input type="radio" name="shuffle-filter" id="commercial" value="commercial">Commercial
          </label>
          <label for="education">
            <input type="radio" name="shuffle-filter" id="education" value="education">Education
          </label>
          <label for="government">
            <input type="radio" name="shuffle-filter" id="government" value="government">Government
          </label>
          <label for="infrastructure">
            <input type="radio" name="shuffle-filter" id="infrastructure" value="infrastructure">Infrastructure
          </label>
          <label for="residential">
            <input type="radio" name="shuffle-filter" id="residential" value="residential">Residential
          </label>
          <label for="healthcare">
            <input type="radio" name="shuffle-filter" id="healthcare" value="healthcare">Healthcare
          </label>
        </div><!-- project filter end -->


        <div class="row shuffle-wrapper">
          <div class="col-1 shuffle-sizer"></div>

          {% for o in object_list %}
          <div class="col-lg-4 col-md-6 shuffle-item" data-groups="[{% for c in o.categories.all %}&quot;{{c.name|lower}}&quot;{% if forloop.counter == 1 %},{% endif %} {% endfor %}]">
            <div class="project-img-container">
              <a class="gallery-popup" href="{{o.image.url}}">
                <img class="img-fluid" src="{{o.image.url}}" alt="project-image">
                <span class="gallery-icon"><i class="fa fa-plus"></i></span>
              </a>
              <div class="project-item-info">
                <div class="project-item-info-content">
                  <h3 class="project-item-title">
                    <a href="{% url 'constra:project-detail' o.id %}">{{o.name}}</a>
                  </h3>
                  <p class="project-cat">{% for c in o.categories.all %} {{c.name}}{% if forloop.counter == 1 %},{% endif %} {% endfor %}</p>
                </div>
              </div>
            </div>
          </div><!-- shuffle item 1 end -->
          {% endfor %}

        </div><!-- shuffle end -->
      </div>

      <div class="col-12">
        <div class="general-btn text-center">
          <a class="btn btn-primary" href=" {% url 'constra:project' %} ">View All Projects</a>
        </div>
      </div>

    </div><!-- Content row end -->

  </div><!-- Conatiner end -->
</section><!-- Main container end -->

templates/constra/project/project.html
{% extends 'constra/base/base.html' %}
{% load static %}

{% block content %}
<div id="banner-area" class="banner-area" style="background-image:url({% static 'images/banner/banner1.jpg'%})">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">Project</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="#">Home</a></li>
                      <li class="breadcrumb-item"><a href="#">Project</a></li>
                      <li class="breadcrumb-item active" aria-current="page">All Projects</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 

{% include "constra/project/list.html" %}
{% endblock %}